spring.application.name=dailymotion-Miner
server.port=8081

# URL base de la API de Dailymotion
dailymotion.baseuri=https://api.dailymotion.com

# Valores por defecto para los parámetros
dailymotion.maxVideos=10
dailymotion.maxPages=2

# URL donde está corriendo VideoMiner (el que recibe los datos)
videominer.uri=http://localhost:8080/videominer/channels